# Generated by Django 2.0.7 on 2019-08-19 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Active',
            field=models.TextField(default='this is lol '),
        ),
    ]
